import React,{useEffect,useState}from"react";import{createRoot}from"react-dom/client";import{Home,ListChecks,Users,Trophy,UserRound,Gift,ChevronRight,CheckCircle2,Copy,Send,ShieldCheck,Sparkles}from"lucide-react";import"./styles.css";
const API=import.meta.env.VITE_API_URL||"https://aeromint-v2-backend-production.up.railway.app";const tg=window.Telegram?.WebApp;
const demo=[{id:1,title:"Join AeroMint Channel",reward:500},{id:2,title:"Daily Check-in",reward:250}];
function App(){const[tab,setTab]=useState("home"),[d,setD]=useState({points:0,level:1,dailyProgress:0}),[tasks,setTasks]=useState(demo);
useEffect(()=>{if(tg){tg.ready();tg.expand();tg.setHeaderColor("#07130d");tg.setBackgroundColor("#07130d")}Promise.all([fetch(API+"/api/dashboard").then(r=>r.ok?r.json():null).catch(()=>null),fetch(API+"/api/tasks").then(r=>r.ok?r.json():null).catch(()=>null)]).then(([a,b])=>{if(a)setD(a);if(Array.isArray(b))setTasks(b)});},[]);
const u=tg?.initDataUnsafe?.user,n=u?.first_name||"AeroMiner",un=u?.username?"@"+u.username:"Telegram User",ref=u?.id?`https://t.me/AeroMintXBot?start=ref_${u.id}`:"https://t.me/AeroMintXBot";
const copy=async()=>{await navigator.clipboard?.writeText(ref);tg?.showPopup?.({title:"Referral link",message:"Link copied!",buttons:[{type:"ok"}]})};
return <div className="app"><header><div className="brand"><div className="logo"><Sparkles/></div><div><b>AeroMint</b><small>Airdrop Hub</small></div></div><span className="secure"><ShieldCheck/> Secure</span></header><main>
{tab==="home"&&<><section className="hero card"><p>Welcome back, {n} 👋</p><div className="balance">{(d.points||0).toLocaleString()}<i> AMT</i></div><small>Available balance</small><div className="level"><span>Level {d.level||1}</span><span>{d.dailyProgress||0}% progress</span></div><div className="progress"><div style={{width:`${Math.min(d.dailyProgress||0,100)}%`}}/></div></section><div className="stats"><Stat icon={<Gift/>}label="Daily reward"value="+250 AMT"/><Stat icon={<Users/>}label="Referrals"value="1"/><Stat icon={<Trophy/>}label="Rank"value="#—"/></div><Title t="Quick actions"/><div className="grid"><Action t="Complete Tasks" s="Earn AMT" icon={<ListChecks/>} go={()=>setTab("tasks")}/><Action t="Invite Friends" s="Grow your team" icon={<Users/>} go={()=>setTab("invite")}/></div><Title t="Daily check-in"/><div className="daily card"><Gift/><div><b>Claim your daily reward</b><small>Come back every day for more AMT</small></div><button onClick={()=>setTab("tasks")}>Claim</button></div></>}
{tab==="tasks"&&<><Page t="Tasks" s="Complete activities to earn AMT"/>{tasks.map(x=><div className="task card" key={x.id}><div className="ico"><ListChecks/></div><div><b>{x.title}</b><small>Reward: {x.reward} AMT</small></div><button onClick={()=>setTasks(q=>q.map(z=>z.id===x.id?{...z,done:true}:z))}>{x.done?<CheckCircle2/>:"Start"}</button></div>)}<div className="notice">Rewards will be enabled after secure Telegram verification and server-side task verification.</div></>}
{tab==="invite"&&<><Page t="Invite & Earn" s="Invite friends and grow your team"/><section className="invite card"><Users/><h2>Build your team</h2><p>Share your referral link with friends on Telegram.</p><div className="ref"><span>{ref}</span><button onClick={copy}><Copy/></button></div><button className="primary" onClick={()=>tg?.openTelegramLink?.("https://t.me/share/url?url="+encodeURIComponent(ref))}><Send/> Share link</button></section></>}
{tab==="rank"&&<><Page t="Leaderboard" s="Top AeroMiners by AMT points"/><section className="empty card"><Trophy/><h2>Leaderboard coming next</h2><p>The ranking API will be connected to PostgreSQL next.</p></section></>}
{tab==="profile"&&<><Page t="Profile" s="Your AeroMint account"/><section className="profile card"><div className="avatar">{n[0].toUpperCase()}</div><h2>{n}</h2><p>{un}</p><div className="rows"><div><span>Balance</span><b>{(d.points||0).toLocaleString()} AMT</b></div><div><span>Level</span><b>{d.level||1}</b></div><div><span>Telegram ID</span><b>{u?.id||"—"}</b></div></div></section></>}</main><nav><Nav a={tab==="home"}t="Home"i={<Home/>}go={()=>setTab("home")}/><Nav a={tab==="tasks"}t="Tasks"i={<ListChecks/>}go={()=>setTab("tasks")}/><Nav a={tab==="invite"}t="Invite"i={<Users/>}go={()=>setTab("invite")}/><Nav a={tab==="rank"}t="Rank"i={<Trophy/>}go={()=>setTab("rank")}/><Nav a={tab==="profile"}t="Profile"i={<UserRound/>}go={()=>setTab("profile")}/></nav></div>}
function Stat(p){return <div className="stat card">{p.icon}<div><small>{p.label}</small><b>{p.value}</b></div></div>}function Action(p){return <button className="action card"onClick={p.go}><span>{p.icon}</span><div><b>{p.t}</b><small>{p.s}</small></div><ChevronRight/></button>}function Title({t}){return <h3>{t}</h3>}function Page({t,s}){return <div className="page"><h1>{t}</h1><p>{s}</p></div>}function Nav(p){return <button className={p.a?"active":""}onClick={p.go}>{p.i}<span>{p.t}</span></button>}
createRoot(document.getElementById("root")).render(<App/>);
